name = "lecturer-materials"
main = "src/index.js"
compatibility_date = "2026-04-27"
workers_dev = true

[vars]
CONTACT_EMAIL = "contact@example.com"
RESEND_FROM_EMAIL = "Lecturer Website <onboarding@resend.dev>"
MAIL_FROM_EMAIL = "noreply@example.com"
